services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commerce-frontend
    ports:
      - "4200:80"
    networks:
      - application
    restart: unless-stopped
    depends_on:
      customer-service: 
        condition: service_healthy
      # order-service:
      #   condition: service_healthy
      keycloak:
        condition: service_healthy        

networks:
  application:
    external: true