services:
  keycloak-db:
    image: postgres:17
    container_name: ecom-keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - identity
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${KEYCLOAK_DB_USERNAME} -d ${KEYCLOAK_DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    mem_limit: 256m
    cpus: 0.5      

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.4
    container_name: commerce-keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL:
        jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "9000:8080"
    volumes:
      - ./infrastructure/keycloak/realm:/opt/keycloak/data/import:ro
      - ./infrastructure/keycloak/themes:/opt/keycloak/themes:ro
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - identity
      - application
    mem_limit: 1g
    cpus: 1.0


  mailpit:
    image: axllent/mailpit:latest
    container_name: commerce-mailpit
    ports:
      - "8025:8025"   # interface web
      - "1025:1025"   # SMTP
    networks:
      - application    

volumes:
  keycloak-db-data:

networks:
  application:
    driver: bridge
  identity:
    internal: true