spring:
  application:
    name: ecom-api

  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:abcABC123*}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080