spring:
  application:
    name: customers-service

  datasource:
    url: jdbc:mariadb://mariadb:3306/customer-api
    username: customer-api
    password: customer-api
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true