spring:
  application:
    name: customers-service

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true