services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: customer-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT:-8080}
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
      - application
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 512m
    cpus: 0.5
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s


  mariadb:
    image: mariadb:11.8
    container_name: customers-mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    mem_limit: 256m
    cpus: 0.5

networks:
  backend:
    internal: true
  application:
    driver: bridge

volumes:
  mariadb_data: