spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/commerce-platform
          jwk-set-uri: http://keycloak:8080/realms/commerce-platform/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: customer-service
            client-secret: ${KEYCLOAK_CLIENT_SECRET:}
            authorization-grant-type: client_credentials
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/commerce-platform
            token-uri: http://keycloak:8080/realms/commerce-platform/protocol/openid-connect/token

